---
- hosts: localhost
  
  become: yes
  tasks:
  - name: install prerequisites
    apt:
      name:
        - apt-transport-https
        - ca-certificates 
        - curl 
        - gnupg-agent
        - software-properties-common
      update_cache: yes

  - name: add apt-key
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg

  - name: add docker repo
    apt_repository:
      repo: deb https://download.docker.com/linux/ubuntu focal stable

  - name: install docker 
    apt:
      name: 
        - docker-ce
        - docker-ce-cli
        - containerd.io
      update_cache: yes

  
  - name: add user
    become: yes
    shell: "sudo chmod 666 /var/run/docker.sock"

  - name: install python package manager
    apt:
      name: python3-pip
  
  - name: install python sdk
    pip:
      name:
        - docker

- name: Pull root interview 
  hosts: localhost
  tasks:
  - name: Pull root interview image
    docker_container:
      name: "root-ansible-base"
      image: "rootdevs/reliability-interview-container:201805"
      state: started
      restart_policy: on-failure
      ports: 4567:4567


